version: "3"

services:
  otp-microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:16-alpine
    container_name: otp-microservice
    restart: always
    env_file: 
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "4501:4501" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    networks:
      - otp-network
    command: yarn run start:prod

  mongo:
    container_name: mongo
    image: mongo:4.4.8
    command: mongod --auth
    restart: always
    volumes:
      - mongodata:/data/db
      - .\db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/admin --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - otp-network

  mexpress:
    image: mongo-express:latest
    container_name: mexpress
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/auth
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
      - ME_CONFIG_MONGODB_PORT=27017  
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    restart: always
    # links:
    #   - mongo
    volumes: 
      - mongodata:/data/db
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://mexpress:mexpress@127.0.0.1:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - otp-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge

volumes:
  mongodata:
